title: oiertwo.pet
subtitle: Oier Echaniz' PETsornal webpage
description: >- # this means to ignore newlines until "baseurl:"
          ""

url: "https://oiertwo.pet" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /
    #- text: Blog
    #  url: /blog
    - text: Projects
      url : /projects

# Edit these details

menu_title: Hi there!
menu_subtitle: "<p>I am Oier Echaniz, this is my PETsornal webpage.</p>"
author_logo: Oier2.jpg
author: Oier Echaniz
author_bio:
author_email: "oier.etxaniz@gmail.com"
author_location: Elgoibar
author_website_url: "http://oiertwo.pet"

author_work_experiences:
            - company_name:
              company_logo:
              company_url:
              designation:
              description:
              visibility:

cartas_everywhere:
            - title: Why oiertwo?
              info: home_why_oiertwo.html
            - title: Why .PET?
              info: home_why_pet.html

author_education_details:
              - college_logo:
                college_name:
                college_url:
                college_degree:
                description:
                visibility:


author_project_details:
              - project_thumbnail: pyjokes.png
                project_title: PyJokes
                project_description: pyJokes as a service (pip install pyjokes)
                project_url: https://pyjok.es
                visibility: true
              - project_thumbnail: hatza.png
                project_title: Hatza
                project_description: Science magazine in Basque.
                project_url: http://www.hatza.eus
                visibility: true
              - project_thumbnail: hc.png
                project_title: HackCancer
                project_description: HackCancer initative. Where Health and Science meet.
                project_url: http://www.hackcancer.eu
                visibility: true


# social links
twitter_username: oiertwo
github_username:  oiertwo
facebook_username:
linkedin_username:
behance_username:
instagram_username:
medium_username:
telegram_username:
dribbble_username:
flickr_username:

#for comments using disqus
disqus_shortname:

# wakatime username (coding activity)
wakatime_username:

# formspree (contact form)
formspree_email:

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-156518455-1

# Choose what to show ( can be true or false)
show_author_work_experiences: false
show_author_education_details: false
show_author_project_details: false
show_cartas_everywhere: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-algolia
# - jekyll-archives

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


collections:
 - products

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
